[package]
name = "gen_ten"
version = "0.1.0"
edition = "2021"
description = "Also known as XPoint, GenTen is a C++ like type inffered general purpose programming language."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
